
import java.util.Collection;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class Dialog extends javax.swing.JPanel {

    private LinkedList<String> listaVals;
    private DefaultTableModel model;

    /**
     * Creates new form Dialog
     */
    public Dialog(String[] ar) {
        initComponents();
        listaVals = new LinkedList<String>();
        model = (DefaultTableModel) jTable.getModel();

        for (String string : ar) {
            listaVals.add(string);
        }
        updateTable();
    }

    public String getListaVals() {
        model = (DefaultTableModel) jTable.getModel();
        String str;
        if (model.getRowCount() > 1) {
            str = ""+model.getValueAt(0, 0);
            for (int i = 1; i < model.getRowCount(); i++) {
                str += ":"+model.getValueAt(i, 0);
            }
        }else{
            str = model.getValueAt(0, 0) + ":";
        }
        return str;
    }

    private void updateTable() {
        Collection<String> list = listaVals.subList(0, listaVals.size());
        model.setNumRows(0);
        for (String s : list) {
            String[] ar = new String[1];
            ar[0] = s;
            model.addRow(ar);
        }

        jTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jPanel9.setLayout(new java.awt.BorderLayout());

        jScrollPaneTabla.setAutoscrolls(true);
        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(32767, 300));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(300, 60));
        jScrollPaneTabla.setName(""); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Values"
            }
        ));
        jTable.setCellSelectionEnabled(true);
        jTable.setEnabled(true);
        jScrollPaneTabla.setViewportView(jTable);

        jPanel9.add(jScrollPaneTabla, java.awt.BorderLayout.NORTH);

        jButtonEliminar.setText("Delete");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonEliminar);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel10.add(btnSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int num = jTable.getSelectedRow();
        String s = listaVals.get(num);
        listaVals.remove(s);
        updateTable();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
