
import java.util.Collection;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class JDialog extends javax.swing.JDialog {

    private LinkedList<String> listaVals;
    private DefaultTableModel model;
    private boolean closed;
    final boolean common;

    /**
     * Creates new form JDialog
     */
    public JDialog(java.awt.Frame parent, boolean modal, String[] ar, boolean common) {
        super(parent, modal);
        initComponents();
        closed = false;
        this.common = common;
        listaVals = new LinkedList<String>();
        model = (DefaultTableModel) jTable.getModel();

        for (String string : ar) {
            listaVals.add(string);
        }
        fillTable();
    }

    public String getVals() {
        String union = (common) ? ":" : ",";
        String str;
        if (model.getRowCount() > 1) {
            str = "" + model.getValueAt(0, 0);
            for (int i = 1; i < model.getRowCount(); i++) {
                str += union + model.getValueAt(i, 0);
            }
        } else {
            str = model.getValueAt(0, 0) + "";
        }
        return str;
    }

    public boolean isClosed() {
        return closed;
    }

    private void fillTable() {
        Collection<String> list = listaVals.subList(0, listaVals.size());
        model.setNumRows(0);
        for (String s : list) {
            String[] ar = new String[1];
            ar[0] = s;
            model.addRow(ar);
        }

        jTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 2147483647));
        setPreferredSize(new java.awt.Dimension(300, 438));

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 500));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel9.setMaximumSize(new java.awt.Dimension(300, 800));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 402));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jScrollPaneTabla.setAutoscrolls(true);
        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(300, 600));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(300, 60));
        jScrollPaneTabla.setName(""); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Values"
            }
        ));
        jTable.setCellSelectionEnabled(true);
        jTable.setEnabled(true);
        jScrollPaneTabla.setViewportView(jTable);

        jPanel9.add(jScrollPaneTabla, java.awt.BorderLayout.NORTH);

        jPanel10.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 40));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel10.add(btnAdd);

        btnEliminar.setText("Delete");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel10.add(btnEliminar);

        btnSave.setText("Save Values");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel10.add(btnSave);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int num = jTable.getSelectedRow();
        model.removeRow(num);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        closed = true;
        setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String[] ar = {""};
        model.addRow(ar);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
