/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Collection;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Proxecto_Conxunto extends javax.swing.JFrame {

    private LinkedList<Vars> listaVals;
    private DefaultTableModel model;

    /**
     * Creates new form Prpxecto_Conxunto
     */
    public Proxecto_Conxunto() {
        initComponents();
        listaVals = new LinkedList<Vars>();
        model = (DefaultTableModel) jTable.getModel();

        Scanner sc = null;
        try {
            sc = new Scanner(new File("/etc/environment"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Proxecto_Conxunto.class.getName()).log(Level.SEVERE, null, ex);
        }
        String str;
        while (sc.hasNextLine()) {
            str = sc.nextLine();
            String[] s = str.split("=");
            listaVals.add(new Vars(s[0], s[1]));
        }
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Vars", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 0, 12), java.awt.SystemColor.activeCaptionText)); // NOI18N
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setLayout(new java.awt.BorderLayout());

        jScrollPaneTabla.setAutoscrolls(true);
        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(32767, 300));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(300, 60));
        jScrollPaneTabla.setName(""); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Values"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setCellSelectionEnabled(true);
        jTable.setEnabled(true);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPaneTabla.setViewportView(jTable);

        jPanel9.add(jScrollPaneTabla, java.awt.BorderLayout.NORTH);

        jPanel3.add(jPanel9);

        jButtonEliminar.setText("Delete");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonEliminar);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel10.add(btnSave);

        jPanel3.add(jPanel10);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTable() {
        Collection<Vars> list = listaVals.subList(0, listaVals.size());
        model.setNumRows(0);
        for (Vars r : list) {
            String[] ar = new String[2];
            ar[0] = r.getName();
            ar[1] = r.getValue();
            model.addRow(ar);
        }

        jTable.setModel(model);
    }

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int num = jTable.getSelectedRow();
        Vars r = listaVals.get(num);
        listaVals.remove(r);
        updateTable();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int num = jTable.getSelectedRow();
            Vars v = listaVals.get(num);
            String value = v.getValue();
            value = value.replaceAll("\"", "");
            if (!v.getName().contains("proxy")) {
                String[] split = value.split(":");
                Dialog dialog = new Dialog(split);
                JOptionPane.showMessageDialog(this, dialog);
                System.out.println(dialog.getListaVals());
            }else{
                JOptionPane.showInputDialog(this, null,v.getName(),JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Runtime.getRuntime().exec("reboot");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proxecto_Conxunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proxecto_Conxunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proxecto_Conxunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proxecto_Conxunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proxecto_Conxunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
